#!/usr/bin/env node
/**
 * Builds sitemap.xml from the pages that actually exist on disk.
 *
 *   node scripts/build-sitemap.mjs            rewrite sitemap.xml
 *   node scripts/build-sitemap.mjs --check    fail if it is out of date
 *
 * A sitemap is a promise about which URLs exist. Hand-maintaining one means it
 * is right until somebody adds a product page and forgets, and a sitemap that
 * points at a 404 — or misses half the shop — is worse than not having one.
 * So it is generated, and `npm run check` fails if the file on disk no longer
 * matches what the directory says.
 *
 * A page is in the sitemap when it has a canonical URL and does not carry
 * `noindex`. That is the same pair of facts a crawler uses, read out of the
 * markup rather than kept in a second list here that could disagree with it.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://proteinpoora.shop';
const CHECK = process.argv.includes('--check');

/** Every index.html in the project, ignoring anything not ours. */
function pages(dir = root, found = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) pages(full, found);
    else if (entry.name === 'index.html') found.push(full);
  }
  return found;
}

/** The file's own last commit date, so lastmod is a fact and not "today". */
function lastmod(file) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
      cwd: root, encoding: 'utf8'
    }).trim();
    if (out) return out;
  } catch {
    /* not a git checkout, or the file is not committed yet */
  }
  return new Date().toISOString().slice(0, 10);
}

/** Depth decides how often it changes and how much it matters. */
function weight(url) {
  if (url === '/') return { priority: '1.0', changefreq: 'weekly' };
  if (url.startsWith('/products/')) return { priority: '0.8', changefreq: 'monthly' };
  return { priority: '0.9', changefreq: 'weekly' };
}

const entries = [];
const skipped = [];

for (const file of pages()) {
  const html = readFileSync(file, 'utf8');
  const canonical = /<link rel="canonical" href="([^"]+)">/.exec(html);
  const rel = path.relative(root, file);

  if (!canonical) { skipped.push([rel, 'no canonical link']); continue; }
  if (/<meta name="robots" content="[^"]*noindex/.test(html)) {
    skipped.push([rel, 'noindex']); continue;
  }
  if (!canonical[1].startsWith(SITE)) { skipped.push([rel, 'canonical points elsewhere']); continue; }

  const url = canonical[1].slice(SITE.length) || '/';
  entries.push({ url, loc: canonical[1], lastmod: lastmod(file), ...weight(url) });
}

entries.sort((a, b) => (a.url === '/' ? -1 : b.url === '/' ? 1 : a.url.localeCompare(b.url)));

const xml =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<!-- Generated by scripts/build-sitemap.mjs from the pages on disk. Do not\n' +
  '     edit by hand: `npm run check` fails when this file and the directory\n' +
  '     disagree. A page is listed when it has a canonical URL and no noindex. -->\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  entries.map((e) =>
    '  <url>\n' +
    `    <loc>${e.loc}</loc>\n` +
    `    <lastmod>${e.lastmod}</lastmod>\n` +
    `    <changefreq>${e.changefreq}</changefreq>\n` +
    `    <priority>${e.priority}</priority>\n` +
    '  </url>').join('\n') +
  '\n</urlset>\n';

const out = path.join(root, 'sitemap.xml');

if (CHECK) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  // lastmod moves with every commit, so compare the URL set — that is the
  // part that going stale actually breaks.
  const urls = (s) => (s.match(/<loc>([^<]+)<\/loc>/g) || []).join('\n');
  if (urls(current) !== urls(xml)) {
    console.error('sitemap.xml is out of date. Run: npm run build:sitemap\n');
    console.error('  on disk:  ' + (urls(current).replace(/\n/g, '\n            ') || '(nothing)'));
    console.error('  expected: ' + urls(xml).replace(/\n/g, '\n            '));
    process.exit(1);
  }
  console.log(`sitemap lists ${entries.length} pages, and they are the ones on disk`);
  for (const [file, why] of skipped) console.log(`  not listed: ${file} — ${why}`);
} else {
  writeFileSync(out, xml);
  console.log(`sitemap.xml written — ${entries.length} pages`);
  for (const [file, why] of skipped) console.log(`  not listed: ${file} — ${why}`);
}
